services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: bitzer
      POSTGRES_PASSWORD: bitzer123
      POSTGRES_DB: orders_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bitzer-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: bitzer-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # maps Nginx 80 → host 3000

volumes:
  pgdata:
