"""Add machine_id, machines table, operator to tasks

Revision ID: d9426e524902
Revises: 
Create Date: 2025-08-12 10:45:36.478865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9426e524902'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operationsdb', sa.Column('machine_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'operationsdb', 'machinesdb', ['machine_id'], ['machine_id'])
    op.add_column('tasksdb', sa.Column('operator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasksdb', 'operator')
    op.drop_constraint(None, 'operationsdb', type_='foreignkey')
    op.drop_column('operationsdb', 'machine_id')
    # ### end Alembic commands ###
